name: Second Workflow
on:
  push:
jobs:
    first-job:
      runs-on: ubuntu:latest
      steps:
        - name: greeting
          run: echo "hello deepak sagar"
      concurrency:
        group: ${{ github.workflow }}-first-job
        cancel-in-progress: true